# typed: false
# frozen_string_literal: true

# This file is auto-generated. Do not edit manually.
# Generated by: scripts/generate-homebrew-formula.ts

class Workflowfiesta < Formula
  desc "Terminal interface for WorkflowFiesta AI agents"
  homepage "https://github.com/fiestatools/workflowfiesta-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.2.1/workflowfiesta-darwin-arm64-v0.2.1.tar.gz"
      sha256 "2c9f3d3ca2cf2d12034fe85e3d2e7a63d4cf8fd2784d4339ee0c6e47bddb56e6"
    else
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.2.1/workflowfiesta-darwin-x64-v0.2.1.tar.gz"
      sha256 "245f0d1668f91fe8262f0386a29586c70002580d0c8044c41bdedc493b4bdb88"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.2.1/workflowfiesta-linux-arm64-v0.2.1.tar.gz"
      sha256 "e876a12c9109e37e2f0f27aea29dae6fe63a4b5f7fc1e6129b827c17a9937cf7"
    else
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.2.1/workflowfiesta-linux-x64-v0.2.1.tar.gz"
      sha256 "923421cc446f66ad44d5e824de78ec740560a01a296ede8014ec2cb39aff8775"
    end
  end

  def install
    bin.install "wf"
    # Create workflowfiesta symlink
    bin.install_symlink "wf" => "workflowfiesta"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wf --version")
  end
end
