# typed: false
# frozen_string_literal: true

# This file is auto-generated. Do not edit manually.
# Generated by: scripts/generate-homebrew-formula.ts

class Workflowfiesta < Formula
  desc "Terminal interface for WorkflowFiesta AI agents"
  homepage "https://github.com/fiestatools/workflowfiesta-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.3.0/workflowfiesta-darwin-arm64-v0.3.0.tar.gz"
      sha256 "f6c6201f28ed950045c8f8abb0ac7a0d5de4667cab412c720792271ae12aac1d"
    else
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.3.0/workflowfiesta-darwin-x64-v0.3.0.tar.gz"
      sha256 "491f24c36c4ffae3d0c4854aa13237b6d5af29c876cb5ff04ba381ea152ae5fd"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.3.0/workflowfiesta-linux-arm64-v0.3.0.tar.gz"
      sha256 "110c70fdf171f32c7ee41807dc95da1147cc40ea49d35f81f92533d4159204f7"
    else
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.3.0/workflowfiesta-linux-x64-v0.3.0.tar.gz"
      sha256 "9c8c56a64ffc268c4fd8361d91f4f893766bea511bbece2cac2a5940cf8deafb"
    end
  end

  def install
    bin.install "wf"
    # Create workflowfiesta symlink
    bin.install_symlink "wf" => "workflowfiesta"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wf --version")
  end
end
