# typed: false
# frozen_string_literal: true

# This file is auto-generated. Do not edit manually.
# Generated by: scripts/generate-homebrew-formula.ts

class Workflowfiesta < Formula
  desc "Terminal interface for WorkflowFiesta AI agents"
  homepage "https://github.com/fiestatools/workflowfiesta-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.2.0/workflowfiesta-darwin-arm64-v0.2.0.tar.gz"
      sha256 "5eb4f975f21e50184b0a83a8c055d178bc06797a34b8e7339a4100709699b340"
    else
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.2.0/workflowfiesta-darwin-x64-v0.2.0.tar.gz"
      sha256 "e48fe1dac0127186e9a571c91799211df3ed15e25bd9e1ec71d716ae9fb62db0"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.2.0/workflowfiesta-linux-arm64-v0.2.0.tar.gz"
      sha256 "7b0e5e3894292056d3782c8de85cc553de40eef28456c222b81a5e72f4cf2884"
    else
      url "https://github.com/fiestatools/workflowfiesta-cli/releases/download/v0.2.0/workflowfiesta-linux-x64-v0.2.0.tar.gz"
      sha256 "99cce0b18359eab71846959a30d4c725111a4d74f0570f6f9fcf75cc797c4553"
    end
  end

  def install
    bin.install "wf"
    # Create workflowfiesta symlink
    bin.install_symlink "wf" => "workflowfiesta"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wf --version")
  end
end
